### ISSUE TITLE
翻译问题-第四章 组织你的项目

### ISSUE THREAD

**Issue by hello-code** [spacewander/explore-flask-zh#7]
感谢翻译！感谢你的辛勤工作！
在看到第四章 :组织你的项目 时发现这句话似乎有些不通顺：
yourapp/__init__.py 	`这个文件初始化了你的应用并所有其它的组件组合在一起。`

缺个字“把”？
这个文件初始化了你的应用并`把`所有其它的组件组合在一起

第五章 配置
总结部分的`instance文件夹可以用来将应用的配置替换成当前的变量。` 感觉不好理解，不知道这样理解是否正确：
instance文件夹可以用来改变特定环境的程序配置
再次感谢你的翻译！

**Comment by spacewander** [comment]
过奖了 :smile: 
同样也谢谢你的反馈。
最近工作比较忙，等周末的时候我再仔细看一下吧。

**Comment by spacewander** [comment]
已更新
