### ISSUE TITLE
 电子书

### ISSUE THREAD

**Issue by hello-code** [spacewander/explore-flask-zh#8]
请问有翻译后的pdf或html版本的电子书吗？

**Comment by spacewander** [comment]
你要的PDF已经上传：
http://pan.baidu.com/s/1dDpXTzN

**Comment by hello-code** [comment]
收到！太棒了！
正在看，好像字体有点小。

**Comment by spacewander** [comment]
@hello-code 
试试这个调大了字体的版本：http://pan.baidu.com/s/1sjHtMwP

**Comment by hello-code** [comment]
新版本非常好！谢谢您的辛勤劳动！

**Comment by spacewander** [comment]
哈哈，过奖啦
