### ISSUE TITLE
关于 用户管理的规范 这一章中的疑问

### ISSUE THREAD

**Issue by VishKozus** [spacewander/explore-flask-zh#9]
邮件确认文章中说使用 URLSafeTimedSerializer 方法生成 token。我是初学者，想求教下这个 token 什么时候过期？文章中用 ts.load 判断了是否大于24小时。有没有办法手动将这个 token 过期呢？我是想实现 token 在24小时内过期，并且只能使用一次。用文章中的方法看起来是可以多次使用的。求指点下。

**Comment by spacewander** [comment]
文章里面没有记录token对应的信息，所以没法知道一个token是否已经用过了。如果要想限制token的使用次数，一个思路是把用过的token缓存起来（通过flask-cache之类存在内存里，或存在redis里，记得设置过期时间），检验完后再查找是否用过了。

**Comment by VishKozus** [comment]
你回复的真快。谢谢了。

BTW，翻译的也很好！
